core.entity_form_display.paragraph.d_p_carousel_item.default:
  change:
    expected:
      content:
        field_d_settings:
          type: link
    new:
      content:
        field_d_settings:
          type: link_attributes
