name: Drupal coding standards

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  Verify:
    name: "Verify Drupal conding standards"

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, phpcs

      - name: Download Drupal coding standards
        run: composer global require --no-progress --no-suggest --no-scripts --no-plugins --optimize-autoloader drupal/coder

      - name: Check composer config
        run: composer config --list

      - name: List folder
        run: ls -al ~/.composer/

      - name: Run PHP_CodeSniffer
        run: phpcs -i
